local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  inflation_radius: 0.3

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true

  width: 0.5  # m
  height: 0.5 # m
  resolution: 0.05 # meters/cell
