# Costmap params
shutdown_costmaps: false # Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state

# Frecuency params
controller_frequency: 10.0 # The rate in Hz at which to run the control loop and send velocity commands to the base.
planner_frequency: 1.0 # The rate in Hz at which to run the global planning loop

# Patience params
planner_patience: 5.0 # How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
controller_patience: 15.0 # How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.

# Recovery params
conservative_reset_dist: 3.0 # The distance away from the robot in meters beyond which obstacles will be cleared from the costmap when attempting to clear space in the map

# Oscillation params
oscillation_timeout: 60.0 # How long in seconds to allow for oscillation before executing recovery behaviors
oscillation_distance: 0.2 # How far in meters the robot must move to be considered not to be oscillating
